language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - php tests/tests-creator.php && php tests/tests-parser.php

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


